// SPDX-License-Identifier: MIT
// Copyright (c) Clay Mullis
// Generated by scripts/player_presentation_profiles.py.
#pragma once
#include <arrowbound/GameProfiles.hpp>

namespace zonai_hookshot::playerPresentation::profiles {
struct Functions {
    arrowbound::profiles::Site playerAnimation;
    arrowbound::profiles::Site modelWorld;
    arrowbound::profiles::Site shapeVisible;
    arrowbound::profiles::Site modelBeforeDraw;
    arrowbound::profiles::Site effectCalc;
    arrowbound::profiles::Site effectDestroyed;
    arrowbound::profiles::Site soundCalc;
    arrowbound::profiles::Site soundEmit;
    arrowbound::profiles::Site groundWait;
    arrowbound::profiles::Site groundLockOnWait;
    arrowbound::profiles::Site groundMove;
    arrowbound::profiles::Site groundLockOnMove;
    arrowbound::profiles::Site climbEnter;
    arrowbound::profiles::Site climbLeave;
    arrowbound::profiles::Site floatSetter;
    arrowbound::profiles::Site bodyMerge;
    arrowbound::profiles::Site animatedPose;
    arrowbound::profiles::Site releaseReference;
    arrowbound::profiles::Site currentCommand;
    arrowbound::profiles::Site xlinkComponent;
    arrowbound::profiles::Site boneIndex;
    arrowbound::profiles::Site boneWorld;
    arrowbound::profiles::Site boneLocal;
    arrowbound::profiles::Site setBoneLocal;
    arrowbound::profiles::Site setBoneWorld;
    arrowbound::profiles::Site setMaterialVisible;
    arrowbound::profiles::Site lowerCommand;
    arrowbound::profiles::Site playerYaw;
    arrowbound::profiles::Site turnVelocity;
    arrowbound::profiles::Site setAngularVelocity;
    arrowbound::profiles::Site actionPlayer;
    arrowbound::profiles::Site rightArmCommand;
    arrowbound::profiles::Site parameterIndex;
    arrowbound::profiles::Site parameterFloat;
    arrowbound::profiles::Site setParameterFloat;
    arrowbound::profiles::Site parameterSrt;
    arrowbound::profiles::Site setParameterSrt;
    arrowbound::profiles::Site materialName;
    arrowbound::profiles::Site blackboardIndex;
    arrowbound::profiles::Site getReference;
    arrowbound::profiles::Site bodyMatrix;
};
struct ModelLayout {
    std::size_t skeleton, materialVisibility, materialCount;
};
struct InlineRoute {
    arrowbound::profiles::Site site;
    unsigned ownerRegister;
};
struct Profile {
    arrowbound::profiles::GameVersion version;
    bool nativeTranslation;
    ModelLayout model;
    std::array<InlineRoute, 6> routes;
    Functions functions;
};

inline constexpr Profile kProfiles[]{
    {arrowbound::profiles::GameVersion::V100, false,
     {0x170, 0x148, 0x16A}, {{
    }}, {
        {0x6B25A8, 0xFC190FE8}, // playerAnimation
        {0x72CFE8, 0xD10183FF}, // modelWorld
        {0x29D0944, 0x79402C09}, // shapeVisible
        {0x73DEB8, 0xD10283FF}, // modelBeforeDraw
        {0x72F34C, 0xD10203FF}, // effectCalc
        {0x29EC884, 0xA9BE7BFD}, // effectDestroyed
        {0x8F6ED0, 0xD10283FF}, // soundCalc
        {0xE87710, 0xD10683FF}, // soundEmit
        {0xBA60B8, 0xD101C3FF}, // groundWait
        {0x1D07F84, 0xA9BE7BFD}, // groundLockOnWait
        {0x1D08EC4, 0xA9BE7BFD}, // groundMove
        {0x1D07870, 0xA9BE7BFD}, // groundLockOnMove
        {0x1CF4F2C, 0xD10203FF}, // climbEnter
        {0x1CF72BC, 0xA9BC7BFD}, // climbLeave
        {0x2264C5C, 0xD104C3FF}, // floatSetter
        {0x7C7D34, 0x6DB923E9}, // bodyMerge
        {0x9A8458, 0xD10143FF}, // animatedPose
        {0x80FB90, 0xA9BD7BFD}, // releaseReference
        {0xCD2DFC, 0xD104C3FF}, // currentCommand
        {0x1203CEC, 0xF9411008}, // xlinkComponent
        {0x29CDFC8, 0xA9BD7BFD}, // boneIndex
        {0x29CEAE0, 0xF940B808}, // boneWorld
        {0x29CE9A4, 0xF940B808}, // boneLocal
        {0x29CE860, 0x79402408}, // setBoneLocal
        {0x29CE9F8, 0x79402408}, // setBoneWorld
        {0x29CE7DC, 0xF940A409}, // setMaterialVisible
        {0x6B5618, 0xD10503FF}, // lowerCommand
        {0xBF48B8, 0xD10083FF}, // playerYaw
        {0x16E5DC0, 0xD10243FF}, // turnVelocity
        {0x1076D04, 0xD10083FF}, // setAngularVelocity
        {0x10768CC, 0xF9400408}, // actionPlayer
        {0x15EA030, 0xA9BE7BFD}, // rightArmCommand
        {0x29CE25C, 0xA9BD7BFD}, // parameterIndex
        {0x29CE4D8, 0xF940C008}, // parameterFloat
        {0x29CE50C, 0x39405408}, // setParameterFloat
        {0x29CEF48, 0xF940C008}, // parameterSrt
        {0x29CEFB0, 0x39405408}, // setParameterSrt
        {0x29CE244, 0xF940C008}, // materialName
        {0x2A05F9C, 0xF9406800}, // blackboardIndex
        {0x702ED8, 0xA9BB7BFD}, // getReference
        {0x119756C, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V110, true,
     {0x170, 0x148, 0x16A}, {{
    }}, {
        {0x707EE8, 0xFC190FE8}, // playerAnimation
        {0x759214, 0xD10183FF}, // modelWorld
        {0x2A48CF4, 0x79402C09}, // shapeVisible
        {0x76177C, 0xD10303FF}, // modelBeforeDraw
        {0x7AB068, 0xD10283FF}, // effectCalc
        {0x2A64EC4, 0xA9BE7BFD}, // effectDestroyed
        {0x920790, 0xD10343FF}, // soundCalc
        {0xE9C990, 0xD10683FF}, // soundEmit
        {0xBF3D50, 0xD101C3FF}, // groundWait
        {0x1D76C44, 0xA9BE7BFD}, // groundLockOnWait
        {0x1D77C2C, 0xA9BE7BFD}, // groundMove
        {0x1D76524, 0xA9BE7BFD}, // groundLockOnMove
        {0x1D637A4, 0xD10203FF}, // climbEnter
        {0x1D65B30, 0xA9BC7BFD}, // climbLeave
        {0x22E857C, 0xD104C3FF}, // floatSetter
        {0xA133DC, 0x6DB923E9}, // bodyMerge
        {0x79F708, 0xD10143FF}, // animatedPose
        {0x857990, 0xA9BD7BFD}, // releaseReference
        {0xD6530C, 0xD104C3FF}, // currentCommand
        {0x10F0D34, 0xF9411408}, // xlinkComponent
        {0x2A46308, 0xA9BD7BFD}, // boneIndex
        {0x2A46E28, 0xF940B808}, // boneWorld
        {0x2A46CEC, 0xF940B808}, // boneLocal
        {0x2A46BA8, 0x79402408}, // setBoneLocal
        {0x2A46D40, 0x79402408}, // setBoneWorld
        {0x2A46B24, 0xF940A409}, // setMaterialVisible
        {0x70B1BC, 0xD10503FF}, // lowerCommand
        {0xC1AAE8, 0xD10083FF}, // playerYaw
        {0x172F3D0, 0xD10243FF}, // turnVelocity
        {0x10AF2B4, 0xD10083FF}, // setAngularVelocity
        {0x10AEE90, 0xF9400408}, // actionPlayer
        {0x162E990, 0xA9BE7BFD}, // rightArmCommand
        {0x2A465A4, 0xA9BD7BFD}, // parameterIndex
        {0x2A46820, 0xF940C008}, // parameterFloat
        {0x2A46854, 0x39405408}, // setParameterFloat
        {0x2A47290, 0xF940C008}, // parameterSrt
        {0x2A472F8, 0x39405408}, // setParameterSrt
        {0x2A4658C, 0xF940C008}, // materialName
        {0x2A7E4F4, 0xF9406800}, // blackboardIndex
        {0x752024, 0xA9BB7BFD}, // getReference
        {0xC6E9C4, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V112, true,
     {0x170, 0x148, 0x16A}, {{
    }}, {
        {0x6FC674, 0xFC190FE8}, // playerAnimation
        {0x751824, 0xD10183FF}, // modelWorld
        {0x2A3FE64, 0x79402C09}, // shapeVisible
        {0x7B37A8, 0xD10283FF}, // modelBeforeDraw
        {0x7B0B80, 0xD10283FF}, // effectCalc
        {0x2A5C044, 0xA9BE7BFD}, // effectDestroyed
        {0x90B9B4, 0xD10343FF}, // soundCalc
        {0xE90CC4, 0xD10683FF}, // soundEmit
        {0xBD5AB4, 0xD101C3FF}, // groundWait
        {0x1D6B5A4, 0xA9BE7BFD}, // groundLockOnWait
        {0x1D6C58C, 0xA9BE7BFD}, // groundMove
        {0x1D6AE84, 0xA9BE7BFD}, // groundLockOnMove
        {0x1D58104, 0xD10203FF}, // climbEnter
        {0x1D5A490, 0xA9BC7BFD}, // climbLeave
        {0x22E0AEC, 0xD104C3FF}, // floatSetter
        {0x9F5844, 0x6DB923E9}, // bodyMerge
        {0x791FFC, 0xD10143FF}, // animatedPose
        {0x869D50, 0xA9BD7BFD}, // releaseReference
        {0xC2B7A0, 0xD104C3FF}, // currentCommand
        {0x10E7F14, 0xF9411408}, // xlinkComponent
        {0x2A3D470, 0xA9BD7BFD}, // boneIndex
        {0x2A3DF90, 0xF940B808}, // boneWorld
        {0x2A3DE54, 0xF940B808}, // boneLocal
        {0x2A3DD10, 0x79402408}, // setBoneLocal
        {0x2A3DEA8, 0x79402408}, // setBoneWorld
        {0x2A3DC8C, 0xF940A409}, // setMaterialVisible
        {0x6FF8E8, 0xD10503FF}, // lowerCommand
        {0xC211B8, 0xD10083FF}, // playerYaw
        {0x1723A40, 0xD10243FF}, // turnVelocity
        {0x109F994, 0xD10083FF}, // setAngularVelocity
        {0x109F574, 0xF9400408}, // actionPlayer
        {0x1625300, 0xA9BE7BFD}, // rightArmCommand
        {0x2A3D70C, 0xA9BD7BFD}, // parameterIndex
        {0x2A3D988, 0xF940C008}, // parameterFloat
        {0x2A3D9BC, 0x39405408}, // setParameterFloat
        {0x2A3E3F8, 0xF940C008}, // parameterSrt
        {0x2A3E460, 0x39405408}, // setParameterSrt
        {0x2A3D6F4, 0xF940C008}, // materialName
        {0x2A75764, 0xF9406800}, // blackboardIndex
        {0x7489E4, 0xA9BB7BFD}, // getReference
        {0xCCDE10, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V120, true,
     {0x170, 0x148, 0x16A}, {{
    }}, {
        {0x6C33D4, 0xFC190FE8}, // playerAnimation
        {0x71EE44, 0xD10183FF}, // modelWorld
        {0x2A33CC4, 0x79402C09}, // shapeVisible
        {0x7480B0, 0xD10283FF}, // modelBeforeDraw
        {0x78713C, 0xD10283FF}, // effectCalc
        {0x2A4FE04, 0xA9BE7BFD}, // effectDestroyed
        {0x8BB770, 0xD10343FF}, // soundCalc
        {0xEFC84C, 0xD10683FF}, // soundEmit
        {0xBA0BF0, 0xD101C3FF}, // groundWait
        {0x1D5D5D4, 0xA9BE7BFD}, // groundLockOnWait
        {0x1D5E5BC, 0xA9BE7BFD}, // groundMove
        {0x1D5CEB4, 0xA9BE7BFD}, // groundLockOnMove
        {0x1D4A134, 0xD10203FF}, // climbEnter
        {0x1D4C4C0, 0xA9BC7BFD}, // climbLeave
        {0x22D587C, 0xD104C3FF}, // floatSetter
        {0x7F7090, 0x6DB923E9}, // bodyMerge
        {0x74A8B4, 0xD10143FF}, // animatedPose
        {0x838F50, 0xA9BD7BFD}, // releaseReference
        {0xCC7368, 0xD104C3FF}, // currentCommand
        {0xF615F8, 0xF9411408}, // xlinkComponent
        {0x2A312D8, 0xA9BD7BFD}, // boneIndex
        {0x2A31DF8, 0xF940B808}, // boneWorld
        {0x2A31CBC, 0xF940B808}, // boneLocal
        {0x2A31B78, 0x79402408}, // setBoneLocal
        {0x2A31D10, 0x79402408}, // setBoneWorld
        {0x2A31AF4, 0xF940A409}, // setMaterialVisible
        {0x6C660C, 0xD10503FF}, // lowerCommand
        {0xC01D98, 0xD10083FF}, // playerYaw
        {0x17100F0, 0xD10243FF}, // turnVelocity
        {0x109ED44, 0xD10083FF}, // setAngularVelocity
        {0x109E920, 0xF9400408}, // actionPlayer
        {0x1611E60, 0xA9BE7BFD}, // rightArmCommand
        {0x2A31574, 0xA9BD7BFD}, // parameterIndex
        {0x2A317F0, 0xF940C008}, // parameterFloat
        {0x2A31824, 0x39405408}, // setParameterFloat
        {0x2A32260, 0xF940C008}, // parameterSrt
        {0x2A322C8, 0x39405408}, // setParameterSrt
        {0x2A3155C, 0xF940C008}, // materialName
        {0x2A694D4, 0xF9406800}, // blackboardIndex
        {0x716EDC, 0xA9BB7BFD}, // getReference
        {0xCA56F8, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V121, true,
     {0x170, 0x148, 0x16A}, {{
    }}, {
        {0x69DBC4, 0xFC190FE8}, // playerAnimation
        {0x75B7E4, 0xD10183FF}, // modelWorld
        {0x2A43014, 0x79402C09}, // shapeVisible
        {0x76B6EC, 0xD10283FF}, // modelBeforeDraw
        {0x7C7104, 0xD10283FF}, // effectCalc
        {0x2A5F1E4, 0xA9BE7BFD}, // effectDestroyed
        {0x92E9B0, 0xD10343FF}, // soundCalc
        {0xEF7638, 0xD10683FF}, // soundEmit
        {0xBF77CC, 0xD101C3FF}, // groundWait
        {0x1D69A84, 0xA9BE7BFD}, // groundLockOnWait
        {0x1D6AA6C, 0xA9BE7BFD}, // groundMove
        {0x1D69364, 0xA9BE7BFD}, // groundLockOnMove
        {0x1D565E4, 0xD10203FF}, // climbEnter
        {0x1D58970, 0xA9BC7BFD}, // climbLeave
        {0x22E0590, 0xD104C3FF}, // floatSetter
        {0x843AFC, 0x6DB923E9}, // bodyMerge
        {0x79CC8C, 0xD10143FF}, // animatedPose
        {0x86A288, 0xA9BD7BFD}, // releaseReference
        {0xD2881C, 0xD104C3FF}, // currentCommand
        {0x1066DA0, 0xF9411408}, // xlinkComponent
        {0x2A40628, 0xA9BD7BFD}, // boneIndex
        {0x2A41148, 0xF940B808}, // boneWorld
        {0x2A4100C, 0xF940B808}, // boneLocal
        {0x2A40EC8, 0x79402408}, // setBoneLocal
        {0x2A41060, 0x79402408}, // setBoneWorld
        {0x2A40E44, 0xF940A409}, // setMaterialVisible
        {0x6A0E5C, 0xD10503FF}, // lowerCommand
        {0xC4FEB8, 0xD10083FF}, // playerYaw
        {0x171F740, 0xD10243FF}, // turnVelocity
        {0x107EDC4, 0xD10083FF}, // setAngularVelocity
        {0x107E9A0, 0xF9400408}, // actionPlayer
        {0x161FFE0, 0xA9BE7BFD}, // rightArmCommand
        {0x2A408C4, 0xA9BD7BFD}, // parameterIndex
        {0x2A40B40, 0xF940C008}, // parameterFloat
        {0x2A40B74, 0x39405408}, // setParameterFloat
        {0x2A415B0, 0xF940C008}, // parameterSrt
        {0x2A41618, 0x39405408}, // setParameterSrt
        {0x2A408AC, 0xF940C008}, // materialName
        {0x2A788C4, 0xF9406800}, // blackboardIndex
        {0x753530, 0xA9BB7BFD}, // getReference
        {0xCCB4D4, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V140, true,
     {0x110, 0xE8, 0x10A}, {{
        {{0x559FB8, 0xEB09011F}, 20},
        {{0x55A330, 0xEB09011F}, 20},
        {{0x1721C4, 0xEB09011F}, 19},
        {{0x3A44A0, 0xEB09011F}, 21},
        {{0x3A6118, 0xEB09011F}, 20},
    }}, {
        {0x12DC5C, 0xFC190FE8}, // playerAnimation
        {0xA7CB0, 0xD10183FF}, // modelWorld
        {0x2846018, 0xF9400408}, // shapeVisible
        {0x1062984, 0xD10503FF}, // modelBeforeDraw
        {0x3A676C, 0xB9403008}, // effectCalc
        {0x28D3824, 0x1766E887}, // effectDestroyed
        {0x3AF7E0, 0xB9403008}, // soundCalc
        {0x9E2690, 0xD106C3FF}, // soundEmit
        {0x613364, 0xD10643FF}, // groundWait
        {0x23F7924, 0xA9BE7BFD}, // groundLockOnWait
        {0x23F883C, 0xA9BE7BFD}, // groundMove
        {0x23F7300, 0xA9BE7BFD}, // groundLockOnMove
        {0x23E3E30, 0xD10283FF}, // climbEnter
        {0x23E5C24, 0xA9BB7BFD}, // climbLeave
        {0x293011C, 0x37F801C1}, // floatSetter
        {0x57CA20, 0xF9402409}, // bodyMerge
        {0xB2940, 0xB940400A}, // animatedPose
        {0x80F5A4, 0xD10103FF}, // releaseReference
        {0x87911C, 0x37F80141}, // currentCommand
        {0x2AE9458, 0xF9411408}, // xlinkComponent
        {0x6D7DB0, 0xA9BE7BFD}, // boneIndex
        {0x157AF0, 0xF9408808}, // boneWorld
        {0x62958, 0xF9408808}, // boneLocal
        {0x629E8, 0x79402408}, // setBoneLocal
        {0x283DE04, 0x79402408}, // setBoneWorld
        {0x283DB7C, 0xF9407409}, // setMaterialVisible
        {0x13107C, 0xD10503FF}, // lowerCommand
        {0x1BD9A30, 0xF9400C08}, // playerYaw
        {0x1D0A000, 0xD10243FF}, // turnVelocity
        {0xBEBC10, 0xD10083FF}, // setAngularVelocity
        {0xBEB764, 0xF9400408}, // actionPlayer
        {0x1BDBC0C, 0xA9BE7BFD}, // rightArmCommand
        {0x4EC760, 0xA9BE7BFD}, // parameterIndex
        {0x2CA6CC, 0xF9409008}, // parameterFloat
        {0x4EC6C4, 0x39405008}, // setParameterFloat
        {0x283E248, 0xF9409008}, // parameterSrt
        {0x283E2B0, 0x39405008}, // setParameterSrt
        {0x668B04, 0xF9406C08}, // materialName
        {0x2930220, 0xF9406800}, // blackboardIndex
        {0x2C02CC, 0xD10183FF}, // getReference
        {0xA4A7BC, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V141, true,
     {0x110, 0xE8, 0x10A}, {{
        {{0x3FA008, 0xEB09011F}, 20},
        {{0x3FA384, 0xEB09011F}, 20},
        {{0x15BF0C, 0xEB09011F}, 19},
        {{0x368AA4, 0xEB09011F}, 21},
        {{0x36A5F0, 0xEB09011F}, 21},
        {{0x36B0AC, 0xEB09011F}, 20},
    }}, {
        {0x584210, 0xFC190FE8}, // playerAnimation
        {0x5124C4, 0xD10183FF}, // modelWorld
        {0x283E1F8, 0xF9400408}, // shapeVisible
        {0x10559B8, 0xD10503FF}, // modelBeforeDraw
        {0x36B708, 0xB9403008}, // effectCalc
        {0x28CB584, 0x17615DE7}, // effectDestroyed
        {0x373AB0, 0xB9403008}, // soundCalc
        {0x99F1A0, 0xD106C3FF}, // soundEmit
        {0x7F8A14, 0xD10643FF}, // groundWait
        {0x23E8C88, 0xA9BE7BFD}, // groundLockOnWait
        {0x23E9BA0, 0xA9BE7BFD}, // groundMove
        {0x23E8664, 0xA9BE7BFD}, // groundLockOnMove
        {0x23D5194, 0xD10283FF}, // climbEnter
        {0x23D6F88, 0xA9BB7BFD}, // climbLeave
        {0x292946C, 0x37F801C1}, // floatSetter
        {0x422E20, 0xF9402409}, // bodyMerge
        {0x564D30, 0xB940400A}, // animatedPose
        {0x7EA5A4, 0xD10103FF}, // releaseReference
        {0x8AB18C, 0x37F80141}, // currentCommand
        {0x2AE2B78, 0xF9411408}, // xlinkComponent
        {0x67F700, 0xA9BE7BFD}, // boneIndex
        {0xBBF30, 0xF9408808}, // boneWorld
        {0xAC4A8, 0xF9408808}, // boneLocal
        {0xAC538, 0x79402408}, // setBoneLocal
        {0x28328E4, 0x79402408}, // setBoneWorld
        {0x283265C, 0xF9407409}, // setMaterialVisible
        {0x5876D8, 0xD10503FF}, // lowerCommand
        {0x1BCB810, 0xF9400C08}, // playerYaw
        {0x1CFC010, 0xD10243FF}, // turnVelocity
        {0xBC26C0, 0xD10083FF}, // setAngularVelocity
        {0xBC21F0, 0xF9400408}, // actionPlayer
        {0x1BCD9EC, 0xA9BE7BFD}, // rightArmCommand
        {0x5B7FF0, 0xA9BE7BFD}, // parameterIndex
        {0x21B8C8, 0xF9409008}, // parameterFloat
        {0x5B7F58, 0x39405008}, // setParameterFloat
        {0x2832D28, 0xF9409008}, // parameterSrt
        {0x2832D90, 0x39405008}, // setParameterSrt
        {0x697D34, 0xF9406C08}, // materialName
        {0x2929570, 0xF9406800}, // blackboardIndex
        {0x4D421C, 0xD10183FF}, // getReference
        {0xA1BBA8, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V142, true,
     {0x110, 0xE8, 0x10A}, {{
        {{0x422028, 0xEB09011F}, 20},
        {{0x4223B0, 0xEB09011F}, 20},
        {{0xCEBBC, 0xEB09011F}, 19},
        {{0x1C89B0, 0xEB09011F}, 21},
        {{0x1CAC2C, 0xEB09011F}, 20},
    }}, {
        {0x5AA820, 0xFC190FE8}, // playerAnimation
        {0x52351C, 0xD10183FF}, // modelWorld
        {0x283E578, 0xF9400408}, // shapeVisible
        {0x1052DA0, 0xD10503FF}, // modelBeforeDraw
        {0x1CB280, 0xB9403008}, // effectCalc
        {0x28CB320, 0x176527E0}, // effectDestroyed
        {0x1D3B68, 0xB9403008}, // soundCalc
        {0x9B0C54, 0xD106C3FF}, // soundEmit
        {0x606048, 0xD10643FF}, // groundWait
        {0x23E92FC, 0xA9BE7BFD}, // groundLockOnWait
        {0x23EA214, 0xA9BE7BFD}, // groundMove
        {0x23E8CD8, 0xA9BE7BFD}, // groundLockOnMove
        {0x23D5808, 0xD10283FF}, // climbEnter
        {0x23D75FC, 0xA9BB7BFD}, // climbLeave
        {0x29284D4, 0x37F801C1}, // floatSetter
        {0x448C50, 0xF9402409}, // bodyMerge
        {0x51F560, 0xB940400A}, // animatedPose
        {0x87AE18, 0xD10103FF}, // releaseReference
        {0x47BE00, 0x37F80141}, // currentCommand
        {0x2AE313C, 0xF9411408}, // xlinkComponent
        {0x7234A0, 0xA9BE7BFD}, // boneIndex
        {0xA5828, 0xF9408808}, // boneWorld
        {0x413994, 0xF9408808}, // boneLocal
        {0x723420, 0x79402408}, // setBoneLocal
        {0x2832D40, 0x79402408}, // setBoneWorld
        {0x2832AB8, 0xF9407409}, // setMaterialVisible
        {0x5ADCDC, 0xD10503FF}, // lowerCommand
        {0x1BC90CC, 0xF9400C08}, // playerYaw
        {0x1CFB180, 0xD10243FF}, // turnVelocity
        {0xBB8E10, 0xD10083FF}, // setAngularVelocity
        {0xBB8940, 0xF9400408}, // actionPlayer
        {0x1BCB2A8, 0xA9BE7BFD}, // rightArmCommand
        {0x493B60, 0xA9BE7BFD}, // parameterIndex
        {0x22FE24, 0xF9409008}, // parameterFloat
        {0x493AC4, 0x39405008}, // setParameterFloat
        {0x2833184, 0xF9409008}, // parameterSrt
        {0x28331EC, 0x39405008}, // setParameterSrt
        {0x6D1274, 0xF9406C08}, // materialName
        {0x29285D8, 0xF9406800}, // blackboardIndex
        {0x6570B0, 0xD10183FF}, // getReference
        {0x201614, 0xA9BD7BFD}, // bodyMatrix
    }},
    {arrowbound::profiles::GameVersion::V143, true,
     {0x110, 0xE8, 0x10A}, {{
        {{0x24CD08, 0xEB09011F}, 20},
        {{0x24D080, 0xEB09011F}, 20},
        {{0x7DA08, 0xEB09011F}, 19},
        {{0x3927DC, 0xEB09011F}, 21},
        {{0x394310, 0xEB09011F}, 21},
        {{0x394EC8, 0xEB09011F}, 20},
    }}, {
        {0x4DD6D0, 0xFC190FE8}, // playerAnimation
        {0x45171C, 0xD10183FF}, // modelWorld
        {0x284CE18, 0xF9400408}, // shapeVisible
        {0x104F4F0, 0xD10503FF}, // modelBeforeDraw
        {0x395500, 0xB9403008}, // effectCalc
        {0x28DB7C8, 0x17623196}, // effectDestroyed
        {0x39D144, 0xB9403008}, // soundCalc
        {0x963904, 0xD106C3FF}, // soundEmit
        {0x83D714, 0xD10643FF}, // groundWait
        {0x23F50C8, 0xA9BE7BFD}, // groundLockOnWait
        {0x23F5FE0, 0xA9BE7BFD}, // groundMove
        {0x23F4AA4, 0xA9BE7BFD}, // groundLockOnMove
        {0x23E15D4, 0xD10283FF}, // climbEnter
        {0x23E33C8, 0xA9BB7BFD}, // climbLeave
        {0x293905C, 0x37F801C1}, // floatSetter
        {0x2752C8, 0xF9402409}, // bodyMerge
        {0x4BDBD0, 0xB940400A}, // animatedPose
        {0x7C1E08, 0xD10103FF}, // releaseReference
        {0x2AD40C, 0x37F80141}, // currentCommand
        {0x2AF5338, 0xF9411408}, // xlinkComponent
        {0x8273D0, 0xA9BE7BFD}, // boneIndex
        {0xABEC, 0xF9408808}, // boneWorld
        {0x34D950, 0xF9408808}, // boneLocal
        {0x34D9E0, 0x79402408}, // setBoneLocal
        {0x28446D4, 0x79402408}, // setBoneWorld
        {0x284444C, 0xF9407409}, // setMaterialVisible
        {0x4E0AAC, 0xD10503FF}, // lowerCommand
        {0x1BCC0D4, 0xF9400C08}, // playerYaw
        {0x1CFE510, 0xD10243FF}, // turnVelocity
        {0xBD3B70, 0xD10083FF}, // setAngularVelocity
        {0xBD3698, 0xF9400408}, // actionPlayer
        {0x1BCE2A4, 0xA9BE7BFD}, // rightArmCommand
        {0x77A390, 0xA9BE7BFD}, // parameterIndex
        {0x151D08, 0xF9409008}, // parameterFloat
        {0x77A2F8, 0x39405008}, // setParameterFloat
        {0x2844B18, 0xF9409008}, // parameterSrt
        {0x2844B80, 0x39405008}, // setParameterSrt
        {0x5B6300, 0xF9406C08}, // materialName
        {0x2939240, 0xF9406800}, // blackboardIndex
        {0x1AFBE4, 0xD10183FF}, // getReference
        {0xA14D78, 0xA9BD7BFD}, // bodyMatrix
    }},
};

inline const Profile* find(arrowbound::profiles::GameVersion version) {
    for (const auto& profile : kProfiles)
        if (profile.version == version) return &profile;
    return nullptr;
}
}
